from typing import Any

class Geometry: ...
class ShapelyError(Exception): ...
class GEOSException(ShapelyError): ...
class STRtree: ...

area: Any
boundary: Any
bounds: Any
box: Any
buffer: Any
build_area: Any
centroid: Any
clip_by_rect: Any
concave_hull: Any
contains: Any
contains_properly: Any
contains_xy: Any
convex_hull: Any
count_coordinate: Any
coverage_union: Any
covered_by: Any
covers: Any
create_collection: Any
crosses: Any
delaunay_triangles: Any
destroy_prepared: Any
difference: Any
difference_prec: Any
disjoint: Any
distance: Any
dwithin: Any
envelope: Any
equals: Any
equals_exact: Any
extract_unique_points: Any
force_2d: Any
force_3d: Any
frechet_distance: Any
frechet_distance_densify: Any
from_geojson: Any
from_wkb: Any
from_wkt: Any
geos_capi_version: tuple[int, int, int]
geos_capi_version_string: str
geos_version: tuple[int, int, int]
geos_version_string: str
get_coordinate_dimension: Any
get_coordinates: Any
get_dimensions: Any
get_exterior_ring: Any
get_geometry: Any
get_interior_ring: Any
get_num_coordinates: Any
get_num_geometries: Any
get_num_interior_rings: Any
get_num_points: Any
get_point: Any
get_precision: Any
get_srid: Any
get_type_id: Any
get_x: Any
get_y: Any
get_z: Any
has_z: Any
hausdorff_distance: Any
hausdorff_distance_densify: Any
intersection: Any
intersection_all: Any
intersection_prec: Any
intersects: Any
intersects_xy: Any
is_ccw: Any
is_closed: Any
is_empty: Any
is_geometry: Any
is_missing: Any
is_prepared: Any
is_ring: Any
is_simple: Any
is_valid: Any
is_valid_input: Any
is_valid_reason: Any
length: Any
line_interpolate_point: Any
line_interpolate_point_normalized: Any
line_locate_point: Any
line_locate_point_normalized: Any
line_merge: Any
line_merge_directed: Any
linearrings: Any
linestrings: Any
make_valid: Any
minimum_bounding_circle: Any
minimum_bounding_radius: Any
minimum_clearance: Any
node: Any
normalize: Any
offset_curve: Any
oriented_envelope: Any
overlaps: Any
point_on_surface: Any
points: Any
polygonize: Any
polygonize_full: Any
polygons: Any
prepare: Any
registry: Any
relate: Any
relate_pattern: Any
remove_repeated_points: Any
reverse: Any
segmentize: Any
set_coordinates: Any
set_precision: Any
set_srid: Any
shared_paths: Any
shortest_line: Any
simplify: Any
simplify_preserve_topology: Any
snap: Any
symmetric_difference: Any
symmetric_difference_all: Any
symmetric_difference_prec: Any
to_geojson: Any
to_wkb: Any
to_wkt: Any
touches: Any
unary_union: Any
unary_union_prec: Any
union: Any
union_prec: Any
voronoi_polygons: Any
within: Any
