from .geometry.base import BaseGeometry

class PreparedGeometry:
    context: BaseGeometry
    prepared: bool
    def __init__(self, context: BaseGeometry | PreparedGeometry) -> None: ...
    def contains(self, other: BaseGeometry) -> bool: ...
    def contains_properly(self, other: BaseGeometry): ...
    def covers(self, other: BaseGeometry): ...
    def crosses(self, other: BaseGeometry): ...
    def disjoint(self, other: BaseGeometry): ...
    def intersects(self, other: BaseGeometry): ...
    def overlaps(self, other: BaseGeometry): ...
    def touches(self, other: BaseGeometry): ...
    def within(self, other: BaseGeometry): ...
    def __reduce__(self): ...

def prep(ob: BaseGeometry) -> PreparedGeometry: ...
